- lib/index.js
- lib/mdl/Card.js
- lib/mdl/index.js
I'm trying to implement mdl's cards but I'm not happy with the public API in this PR. 
The current result :
With it, we can do something like : 
```javascript
const Cards = React.createClass({
render(){
var base64Icon = 'http://www.getmdl.io/assets/demos/welcome_card.jpg';
var content = (<Text style={{color: "rgba(0,0,0,.54)"}}>
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Mauris sagittis pellentesque lacus eleifend lacinia...
</Text>)
var action = (<Text> My action</Text>);
var menu = (
<MKIconToggle
checked={true}
onCheckedChange={this._onIconChecked}
onPress={this._onIconClicked}
>
<Text pointerEvents="none"
style={styles.toggleTextOff}>Off</Text>
<Text state_checked={true}
pointerEvents="none"
style={[styles.toggleText, styles.toggleTextOn]}>On</Text>
</MKIconToggle>
); …
```
> [WIP] First step to implement cards

- lib/mdl/Slider.js
Replace MKTouchable to React Native PanResponder for touch handling
Closes #52
> Using PanResponder for Slider component

- README.md
MK is not defined in the example code.
> Updating the example code for the Card style

- lib/mdl/RadioButton.js
> Added confirmUncheck method for Group.onChecked to call on.

- lib/mdl/Textfield.js
This make the onBlur and onFocus behave the same as TextInput
> added event object to blur and focus

- package.json
this follows a recommendation raised by @brentvatne : https://twitter.com/notbrent/status/684107286994796544
> remove peerDependencies constraint

- lib/mdl/RangeSlider.js
Hi,
I am using react-native-material-kit in my project and I needed a step property for the range slider.
Here is my solution:
Default step = 1,
Step must be a divisor of max, in order to work, otherwise throw an error
> Added step to range slider

- lib/MKPropTypes.js
- lib/builder.js
- lib/internal/MKTouchable.js
- lib/internal/Thumb.js
- lib/internal/Tick.js
- lib/mdl/Button.js
- lib/mdl/Checkbox.js
- lib/mdl/IconToggle.js
- lib/mdl/IndeterminateProgress.js
- lib/mdl/Progress.js
- lib/mdl/RadioButton.js
- lib/mdl/RangeSlider.js
- lib/mdl/Ripple.js
- lib/mdl/Slider.js
- lib/mdl/Spinner.android.js
- lib/mdl/Spinner.ios.js
- lib/mdl/Switch.js
- lib/mdl/Textfield.js
- lib/theme.js
Update imports to ES6/7 Styling
> Update imports to ES6/7 Styling

- README.md
> Add RNPM to Readme

- lib/utils.js
Added testID's to buttons in order to be able to make UITests
> Fixed issue with buttons missing testID

- lib/mdl/Slider.js
This is an adaptation of the existing feature in `RangeSlider` for `Slider`
> added snapping to step (with default step = 1)

- lib/mdl/IconToggle.js
> Fix #178 by adding props.style

- lib/mdl/Textfield.js
I was having issues with this.refs.input being undefined in the setPlaceHolder(placeholder) method, I added a check and only update the place holder if it is defined.
> Added this.refs.input check

- lib/mdl/RangeSlider.js
I need initialization slider. So I added this function.
I think some people really need this function.
> Add _rollbackSlider

- lib/mdl/Switch.js
> Fix Switch issue with setState

- README.md
In RN 0.32 the last manual step is in MainApplication.java rather than MainActivity.java
> Tweak Java manual steps for RN 0.32

- lib/mdl/RangeSlider.js
Causes compile errors in React-Native.
> Added missing semicolon

- lib/mdl/Textfield.js
I was trying to clean up my machine and found I had missed a save before I committed.  I just a little bit of the documentation text.
> [PR 280 revision] Adding the last bit of text missed in previous commit. 

- package.json
Please update [ramda](https://npmjs.org/package/ramda) to version 0.23.0.
If this passes your tests you can merge it in.  If not please use this branch for changes.
* [```5dec606```](https://github.com/ramda/ramda/commit/5dec606e0504af973cd6e0ceec8997b72800eb6b) ```Version 0.23.0```
* [```8a5ca01```](https://github.com/ramda/ramda/commit/8a5ca01147c7445799bfb2381b771bdfb61676fa) ```Fix tail function length (#2020)```
* [```6fdbe27```](https://github.com/ramda/ramda/commit/6fdbe27d286bbbbc9c97049a6b3c3b11cc01b434) ```Use _xfBase for XDropRepeatsWith (#2001)```
* [```0c45a57```](https://github.com/ramda/ramda/commit/0c45a57fc955317f129be04ad2344dd1c98713bf) ```Merge pull request #1992 from asaf-romano/set-functions-equality```
* [```f63e924```](https://github.com/ramda/ramda/commit/f63e92411 …
> Updating ramda to 0.23.0

- README.md
- lib/mdl/Ripple.js
This allows the animation to occur in a native thread so that JavaScript code execution resulting from an "onPress" does not block the animation's completion.
https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html
> add useNativeDriver to Ripple animations

- README.md
Fixing issue #309 : 
I have updated readme file by adding solution if you found problem when you follow manually android, please check my PR thanks.
> #309 update readme

- lib/mdl/RangeSlider.js
> fix(RangeSlider): step not working when min > 0

- README.md
> update (README.md): removed $ from terminal commands

- android/src/main/java/com/github/xinthink/rnmk/widget/MKSpinner.java
Prevent issue https://github.com/xinthink/react-native-material-kit/issues/345
> Prevent NPE when rect is null

- src/mdl/Checkbox.tsx
Fixes the condition added in #410
> Another patch for #410 PR

- android/build.gradle
> Optionally pull in project SDK versions
