- README.md
- react-native-material-kit.podspec
adding pod spec to the project so installing the project in a cocoapods react native project should be as simple as:
```ruby
pod 'react-native-material-kit', :path => 'node_modules/react-native-material-kit'
```
full example:
```ruby
xcodeproj 'ios/Example.xcodeproj/'
pod 'React', :subspecs => ['Core', 'RCTText', 'RCTWebSocket'], :path => 'node_modules/react-native'
pod 'react-native-material-kit', :path => 'node_modules/react-native-material-kit'
post_install do |installer|
target = installer.pods_project.targets.select{|t| 'React' == t.name}.first
phase = target.new_shell_script_build_phase('Run Script')
phase.shell_script = "if nc -w 5 -z localhost 8081 ; then\n  if ! curl -s \"http://localhost:8081/status\" | grep -q \"packager-status:running\" ; then\n    echo \"Port 8081 already in …
```
> Adding pod spec. closes #27

- lib/mdl/cards/styles.js
Fixed by setting width to 1, and borderColor same as background.
> Border doesn't show up when width is 0.

- android/build.gradle
Revert to buildToolsVersion '23.0.1' to fix xinthink/react-native-material-kit#77
> Revert to buildToolsVersion '23.0.1'

- lib/mdl/Textfield.js
I’m using the previous buffered value as a fall back if new props do
not have a value.
> Fixes disappearing floating label

- lib/mdl/Textfield.js
- lib/theme.js
Adds scale + color transitions to the floating label animation. See the attached image:
Tested on both iOS and Android.
> Improve floating label animations

- android/src/main/java/com/github/xinthink/rnmk/widget/TickView.java
Leaving 2px gap from bottom to appear more central. 
(let's remember, as you know [Google leave min. 2 px gap](https://www.google.com/design/spec/style/icons.html#icons-system-icons) between two border line)
> Correcting the tick position

- lib/internal/Thumb.js
- lib/mdl/Slider.js
If the slider components are placed within components that respond to gestures, the parent component's gesture overrides the slider's gesture.
See #114.
Deny termination requests from other components while dragging the slider thumbs.
> Prevent pan termination request while dragging slider thumbs

- lib/internal/Thumb.js
- lib/mdl/RangeSlider.js
- lib/mdl/Slider.js
My app needs to disable scrolling while the sliders are being dragged. I tried using the `onChange` callbacks, but the `onChange` callbacks continue to fire after the `onConfirm` callback is fired.
As a workaround, I added an `onStart` callback that fires when dragging begins. This allows me to disable scrolling at the start of the drag event, and then to disable it at the end of the drag event using the `onConfirm` callback.
~~~javascript
class MyComponent extends React.Component {
// disable scrolling while dragging range sliders
onStart () {
this.setState({scrollEnabled: false});
}
onChange ({min, max}) {
// handle change
}
// re-enable scrolling when range selection is complete
onConfirm () {
this.setState({scrollEnabled: true});
}
render () {
<ScrollView …
> Add onStart callback to MKRangeSlider

- lib/mdl/Checkbox.js
We are disabling our inputs while the form is being submitted. Having this editable prop simplifies that and I'm sure others will find it useful as well. It also stays inline with how the built-in \<TextInput /\> works.
Let me know if here are any changes or additions you'd like to make.
> Added editable prop to checkbox

- lib/mdl/Textfield.js
https://getmdl.io/components/index.html also has 2 px underline (when text is being entered into the textfield)
> change default underline size

- lib/mdl/Textfield.js
Font scaling is when the user changes the global device font size/scale. Standard for Text and TextInput are true (they will scale the font size according to the device setting). This pull request adds an option to disable it on TextFields (automatically does it on it's FloatingLabel too) .
> Adds allowFontScaling to TextField and it's FloatingLabel

- lib/mdl/Slider.js
When the value prop is updated the thumb position should be moved accordingly.
> Update thumb position for changing slider value

- lib/mdl/RangeSlider.js
Bug: Range Slider, right now its not setting the new range provided through props and also not updating the view (after component is loaded).
Range Slider should update itself when props are updated after component is loaded.
> range slider should update itself when props are updated

- README.md
In the section about customizing text field, the name of the const and the component used in the example were different, fixed it.
> Fixes small naming error

- lib/mdl/Switch.js
This is to fix crash when toggling MKSwitch (RN0.33.0).
> Fix crash when toggling MKSwitch (RN0.33.0)

- README.md
Since [this commit](https://github.com/facebook/react-native/issues/2768), shadows are now available on Android. Hooray!
> Remove note about shadows being unavailable on Android

- lib/mdl/Textfield.js
[Issue #208](https://github.com/xinthink/react-native-material-kit/issues/208).
When I tap on placeholder the input not focus, because is rendering before the floatingLabel. In react, which it is rendered first matter.
> fix "Can't tap into a field if I tap its placeholder, when floatingLbelEnabled={true}"

- lib/mdl/Textfield.js
I ran into the issue mentioned in https://github.com/xinthink/react-native-material-kit/issues/233. 
As I'm using RN 0.29 and cannot upgrade to 0.33 any time soon and I'm sure there'd be some others people in the same boat, I think the library should facilitate to those cannot afford to upgrade RN.
This address the change introduced in patch https://github.com/xinthink/react-native-material-kit/pull/232
> [Textfield] check label._component is defined before making method call

- lib/mdl/Ripple.js
- lib/mdl/Textfield.js
This fixes an inconsistency with ES6 module import syntax. Since there is no default export for MKPropTypes, this is sometimes undefined.
> fix for MKPropTypes not having a default export

- lib/mdl/Textfield.js
I think this happens only in newer React Native versions.
> Fix 2 underlines below MKTextField on Android

- lib/internal/MKTouchable.js
- lib/mdl/Ripple.js
- lib/mdl/Textfield.js
I was getting undefined `this.refs.label.refs.node.measure()` warnings on `FloatingLabel.measure()` so used `findNodeHandle` and `UIManager.measure()`, which also makes it safer from future updates perspective.
> use UIManager.measure() instead of private refs

- lib/internal/MKTouchable.js
Add `nativeBackgroundAndroid` and `nativeForegroundAndroid` (added in React-Native 0.36 [(6d175f2)](https://github.com/facebook/react-native/commit/6d175f2c257fe1acb1c36b15bc97bdb77560885c)) as nativeOnly props to fix `no propType for native prop` error on Android
> fix `no propType for native prop` error on Android on RN 0.36

- README.md
The link showed 404 error on props reference of icon toggle.
> Fix missing link of icon toggle in README.

- lib/mdl/Ripple.js
Currently, `Ripple` doesn't respect `disabled` prop. So, if you for example set `disabled` prop for `MKRadioButton` to true, it will still animate and change the visual state of the radio button (other components using Ripple might also be suffering from this). This change fixes it.
> Added check to respect the disabled prop

- lib/internal/Thumb.js
- lib/mdl/RangeSlider.js
- lib/mdl/Slider.js
- Thumb component can handle a touchPadding prop
- touchPadding sets hitSlop on Animated.View
- RangeSlider and Slider can handle a thumbPadding prop
- thumbPadding prop passed down as touchPadding on Thumb component
> feat(Thumb): Add optional hitSlop to Thumb for RangeSlider and Slider

- lib/mdl/Textfield.js
(Fix unconstraint sizing in main axis), this allows the textinput to honor height and also does not trims down charachters like 'g & p'.
for more details please refer here https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27
> fixing an issue occuring due to a change made in v0.36

- lib/mdl/Textfield.js
Adding a static fix for the issue.  Could update with a dynamic solution if preferred.
> [Issue 269] Index prop necessary for dynamic input textfield.

- lib/mdl/RadioButton.js
Fixed issue #215 RadioButton setState on unmounted components: causing possible memory leak, and setting states on components that may no longer exist or be mounted. Added events for Group onAdd and onRemove to group to allow user memory maps (for named Groups) to also be maintained. If onAdd or onRemove return false then the operation will be aborted... allowing the user to control which RadioButtons are allowed in / out of the group (if they so wish).
> Fixed issue #215

- lib/internal/MKTouchable.js
- lib/internal/Thumb.js
- lib/internal/Tick.js
- lib/mdl/IndeterminateProgress.js
- lib/mdl/Progress.js
- lib/mdl/RangeSlider.js
- lib/mdl/Ripple.js
- lib/mdl/Slider.js
- lib/mdl/Spinner.android.js
- lib/mdl/Switch.js
React native moved View.propTypes to ViewPropTypes. This pr makes that change, solving the warnings in console. 
See commit here https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396
> Replaced View.propTypes to ViewPropTypes

- lib/MKPropTypes.js
- lib/internal/MKTouchable.js
- lib/internal/Thumb.js
- lib/internal/Tick.js
- lib/mdl/Button.js
- lib/mdl/Checkbox.js
- lib/mdl/IconToggle.js
- lib/mdl/IndeterminateProgress.js
- lib/mdl/Progress.js
- lib/mdl/RadioButton.js
- lib/mdl/RangeSlider.js
- lib/mdl/Ripple.js
- lib/mdl/Slider.js
- lib/mdl/Spinner.android.js
- lib/mdl/Spinner.ios.js
- lib/mdl/Switch.js
- lib/mdl/Textfield.js
- lib/utils.js
- package.json
- yarn.lock
PropTypes has been deprecated from the react package and moved to the 'prop-types' library in reactv15.5, so it currently shows errors in react native projects.
This PR makes that change to the `prop-types` library.
> Replaced React.PropTypes with PropTypes

- lib/internal/MKTouchable.js
- lib/internal/Thumb.js
- lib/internal/Tick.js
- lib/mdl/IndeterminateProgress.js
- lib/mdl/Progress.js
- lib/mdl/RangeSlider.js
- lib/mdl/Ripple.js
- lib/mdl/Slider.js
- lib/mdl/Spinner.android.js
- lib/mdl/Spinner.ios.js
- lib/mdl/Switch.js
- lib/utils.js
Another PR has already made the ViewPropTypes fix for new versions of react native. However that fix broke support with older versions of react. (Since they don't have ViewPropTypes). 
This PR fixes that, by using ViewPropTypes for newer versions and falls back to View.propTypes for older versions
> ViewPropTypes fix for react native

- iOS/RCTMaterialKit/MKTouchable.h
- iOS/RCTMaterialKit/MKTouchableManager.m
- iOS/RCTMaterialKit/TickViewManager.m
I'm not certain why these were changed in this commit: https://github.com/xinthink/react-native-material-kit/commit/892c35e16c042dedf4d41eb3adb141d616017357, but this breaks the build in Xcode for my project. Restoring the previous version of these imports fixes the issue.
> Fix React imports

- android/src/main/java/com/github/xinthink/rnmk/ReactMaterialKitPackage.java
RN 0.47 removed createJSModules from ReactPackage [commit](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)
> handle RN 0.47 breaking change

- lib/mdl/Switch.js
For resolving [Switch doesn't have a thumb shadow](https://github.com/xinthink/react-native-material-kit/issues/303).
The `elevation` style prop has been used. [Docs](https://facebook.github.io/react-native/docs/view.html#style).
> feat(Switch): Added the elevation style prop for Thumb

- lib/mdl/Slider.js
Hi, I had a use case for the slider being in a swipeable interface. When you tried to use the slider, the page would swipe. An easy way to get around this was to add `onPressIn` and `onPressOut` events to the slider that disabled and enabled the page swiping, respectively.
> Adds onPressIn, onPressOut events for slider

- lib/mdl/Spinner.ios.js
Title pretty much says it all.
Currently spinner is dependent on the UI thread, making it loose its smoothness during heavy operations. Using the native driver remedies this.
The Android one is already a native component.
> Use native driver in iOS spinner

- src/mdl/Checkbox.tsx
This fix will make fix the overflow issue that was seen on Android SDK 26+, where in the checkbox in checked mode, fills the entire screen. This fix also contains a patch that helps in avoiding scenarios where the checkbox doesn't changes it's checked state, (as encountered on iPhone X running iOS 12).
> Overflow fix (Android) & prop not applying fix (iOS)

- src/mdl/Checkbox.tsx
This fix addresses the issue when on devices like iPhone X running iOS 12, when we try to check the checkbox initially, it shows the ripple, and gives it's new state in code but visually it doesn't changes it's state. That is, it looks like it's not checked (whereas internally it is). So, this fix shall fix this inconsistency between internal state and visual state of this component.
> Fix for Checkbox not updating visual state, on iOS
